/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthPagesImport } from './routes/_auth-pages'

// Create/Update Routes

const AuthPagesRoute = AuthPagesImport.update({
  id: '/_auth-pages',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth-pages': {
      id: '/_auth-pages'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthPagesImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '': typeof AuthPagesRoute
}

export interface FileRoutesByTo {
  '': typeof AuthPagesRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth-pages': typeof AuthPagesRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: ''
  fileRoutesByTo: FileRoutesByTo
  to: ''
  id: '__root__' | '/_auth-pages'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthPagesRoute: typeof AuthPagesRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthPagesRoute: AuthPagesRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth-pages"
      ]
    },
    "/_auth-pages": {
      "filePath": "_auth-pages.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
